/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SEMAPHORE_H_RPCGEN
#define _SEMAPHORE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define SEMAPHORE 0x20000000
#define Remote 1

struct semaphore_arg {
    int amount;
    int version;
};
typedef struct semaphore_arg semaphore_arg;

#if defined(__STDC__) || defined(__cplusplus)
#define up 1
extern  void * up_1(semaphore_arg *, CLIENT *);
extern  void * up_1_svc(semaphore_arg *, struct svc_req *);
#define down 2
extern  void * down_1(semaphore_arg *, CLIENT *);
extern  void * down_1_svc(semaphore_arg *, struct svc_req *);
extern int semaphore_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define up 1
extern  void * up_1();
extern  void * up_1_svc();
#define down 2
extern  void * down_1();
extern  void * down_1_svc();
extern int semaphore_1_freeresult ();
#endif /* K&R C */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_semaphore_arg (XDR *, semaphore_arg*);

#else /* K&R C */
extern bool_t xdr_semaphore_arg ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SEMAPHORE_H_RPCGEN */
