/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <pthread.h>
#include "semaphore.h"
#include "status.h"
#include <unistd.h>

CLIENT *clnt;

//void
//semaphore_1(char *host)
//{
//	CLIENT *clnt;
//	void  *result_1;
//	int  up_1_arg;
//	void  *result_2;
//	int  down_1_arg;
//
//#ifndef	DEBUG
//	clnt = clnt_create (host, SEMAPHORE, Remote, "udp");
//	if (clnt == NULL) {
//		clnt_pcreateerror (host);
//		exit (1);
//	}
//#endif	/* DEBUG */
//
//	result_1 = up_1(&up_1_arg, clnt);
//	if (result_1 == (void *) NULL) {
//		clnt_perror (clnt, "call failed");
//	}
//	result_2 = down_1(&down_1_arg, clnt);
//	if (result_2 == (void *) NULL) {
//		clnt_perror (clnt, "call failed");
//	}
//#ifndef	DEBUG
//	clnt_destroy (clnt);
//#endif	 /* DEBUG */
//}

void initClient(char* host){
	clnt = clnt_create (host, SEMAPHORE, Remote, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
}

void semUp(int value, int version){
	int *result;
    semaphore_arg arg;
    arg.amount = value;
    arg.version = version;

	result = up_1(&arg, clnt);
	if (result == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
}

void semDown(int value, int version){
	int *result;
    semaphore_arg arg;
    arg.amount = value;
    arg.version = version;

	result = down_1(&arg, clnt);
	if (result == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
}


int
main (int argc, char *argv[])
{
	char *host;
	int serverStatus;
	if (argc < 4) {
		printf ("usage: %s server_host operation_type value\n", argv[0]);
		exit (1);
	}
	host = argv[1];

    int version = getpid();
    pthread_barrier_t barrier;
    pthread_barrier_init(&barrier, NULL, 2);

    threaddata_t* x = (threaddata_t*)malloc(sizeof(threaddata_t));
    x->pbarrier = &barrier;
    x->version = version;
    x->counter = atoi(argv[2]);

	pthread_t pt;
	pthread_create(&pt,NULL,startServer,x);
    pthread_barrier_wait(&barrier);
	initClient(host);


	if(atoi(argv[2])==0){
        semUp(atoi(argv[3]),version);
	}else{
        semUp(0,version);
        semDown(atoi(argv[3]),version);
	}

    clnt_destroy (clnt);
    pthread_barrier_destroy(&barrier);
	pthread_join(pt, (void**)&serverStatus);
	exit (0);
}
